/**
 *
 */
'use strict';

export const REQUEST_HEATMAP = 'REQUEST_HEATMAP';
export const REQUEST_HEATMAP_SUCCESS = 'REQUEST_HEATMAP_SUCCESS';
export const REQUEST_HEATMAP_FAILURE = 'REQUEST_HEATMAP_FAILURE';

export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const REQUEST_PROJECTS_SUCCESS = 'REQUEST_PROJECTS_SUCCESS';
